### PR TITLE
ci: Wait for both BGP sessions before checking how many there are

### PR DESCRIPTION
**Pull request by ctreatma**

### CODE REVIEW

**Comment by ctreatma** [comment]
**NOTE:** This test is still failing because of a 504 timeout, possibly related to dangling resources left behind by other tests

**Comment by ctreatma** [comment]
I cleared out dangling VRFs and virtual circuits from previous acceptance test runs (updating those tests and/or the resource to properly clean up is a separate item under #320.  The test that is updated in this PR is now passing locally and in CI.

Pass line for updated test: https://github.com/equinix/terraform-provider-equinix/actions/runs/5004498703/jobs/8967176160#step:5:3299

**Comment by ocobleseqx** [comment]
> I cleared out dangling VRFs and virtual circuits from previous acceptance test runs (updating those tests and/or the resource to properly clean up is a separate item under #320. The test that is updated in this PR is now passing locally and in CI.
> 
> Pass line for updated test: https://github.com/equinix/terraform-provider-equinix/actions/runs/5004498703/jobs/8967176160#step:5:3299

the link in your comment refers to the previous failed execution, but I verified that the test passes in https://github.com/equinix/terraform-provider-equinix/actions/runs/5015060940/jobs/8990126628?pr=327#step:5:3299

**Review by ocobleseqx — APPROVED** [review]
it works!

**Pull request merged**
