### PR TITLE
Fix all broken acceptance test 

### PR DESCRIPTION
**Pull request by ocobleseqx**
The objective of this PR is to make the necessary changes so that all acceptance tests pass

Currently the tests are returning several errors and it is not possible to run a complete test. Some of them are failing because they are not aligned with the resources behavior and some others that are correct but the resources functionality contains bugs - #78

### CODE REVIEW

**Comment by ocobleseqx** [comment]
Findings:
- Make file does not include realistic timeouts. Some NE devices can take more than 1 hour in some cases
- Parallel Test function can be replaced with [resource.ParallelTest](https://github.com/hashicorp/terraform/pull/18688)
- Network Device Acc Test :
  - Licenses for Juniper VSRX FW and Cisco CSR SD-WAN must have different files
  - resource_network_device should be able to create a device with an invalid license and get status REGISTRATION_FAILED without returning an error. License should be upgradeable later without recreating the resource
  - testAccNeDeviceACLs does not implement any real check function. It should call Client.GetDeviceACLDetails
  - Required TF_ACC_NETWORK_DEVICE_BILLING_ACCOUNT_NAME parameter to filter accounts with multiple billing accounts
- Network Device Link Acc Test: 
  - Link block not required if metro_code is the same for both devices. Link block must be dynamic.

**Comment by displague** [comment]
@ocobleseqx can you create new issues for the problems that you've identified? We can address what you've provided in this PR based on the improvements contained here and then we can revisit the remaining open issues.

Some of the issues that I previously created may represent some of the test failures you've encountered.

**Comment by ocobleseqx** [comment]
List of acceptance test (checked box means pass test):

### equinix/resource_ecx_l2_connection_acc_test.go 

- [ ] TestAccFabricL2Connection_Port_Single_AWS(t *testing.T)
- [ ] TestAccFabricL2Connection_Port_HA_Azure(t *testing.T)
- [ ] TestAccFabricL2Connection_Device_HA_GCP(t *testing.T)

### equinix/resource_ecx_l2_connection_accepter_acc_test.go:func 
- [ ] TestAccFabricL2Connection_Port_Single_Accepter_AWS(t *testing.T)

### equinix/resource_ecx_l2_serviceprofile_acc_test.go
- [ ] TestAccFabricL2ServiceProfile_Private(t *testing.T)

### equinix/resource_network_acl_template_acc_test.go
- [ ] TestAccNetworkACLTemplate(t *testing.T)
### equinix/resource_network_bgp_acc_test.go
- [ ] TestAccNetworkBGP_CSR1000V_Single_AWS(t *testing.T)
### equinix/resource_network_device_acc_test.
- [ ] TestAccNetworkDevice_CSR1000V_HA_Managed_Sub(t *testing.T)
- [ ] TestAccNetworkDevice_CSR1000V_HA_Self_BYOL(t *testing.T)
- [ ] TestAccNetworkDevice_vSRX_HA_Managed_Sub(t *testing.T)
- [ ] TestAccNetworkDevice_vSRX_HA_Managed_BYOL(t *testing.T)
- [ ] TestAccNetworkDevice_vSRX_HA_Self_BYOL(t *testing.T)
- [ ] TestAccNetworkDevice_PaloAlto_HA_Managed_Sub(t *testing.T)
- [ ] TestAccNetworkDevice_PaloAlto_HA_Self_BYOL(t *testing.T)
- [ ] TestAccNetworkDevice_CSRSDWAN_HA_Self_BYOL(t *testing.T)
- [ ] TestAccNetworkDevice_Versa_HA_Self_BYOL(t *testing.T)
- [ ] TestAccNetworkDevice_CGENIX_HA_Self_BYOL(t *testing.T)

### equinix/resource_network_device_link_acc_test.go
- [ ] TestAccNetworkDeviceLink(t *testing.T) {
### equinix/resource_network_ssh_key_acc_test.go
- [ ] TestAccNetworkSSHKey(t *testing.T)

**Review by displague — APPROVED** [review]
Excellent work, @ocobleseqx! Now to get CI running these.

**Pull request merged**
