### PR TITLE
Move the docs to the expected location for the Terraform Registry 

### PR DESCRIPTION
**Pull request by displague**
Updates the docs to the Terraform Registry standards defined at <https://www.terraform.io/docs/registry/providers/docs.html>.  This will help with the eventual publishing via  https://registry.terraform.io/publish/provider.

These changes were applied in two phases. In the first phase:
* The data source and resource docs were moved from README.md to website/d and website/r.
* The `.erb` and index pages were also created.
* Links were added to relevant APIs when known.

The file names were then modified (and the .erb file was removed) based on the recommendations offered at <https://www.terraform.io/docs/registry/providers/docs.html#migrating-legacy-providers-docs>. 

README.md was modified to link to the Github copies of the resource docs. (I think I got these linked in a way that will work on Github after merge).

Ideally, these links would be changed to refer to the docs once they are available on the Terraform Provider Registry.

### CODE REVIEW

**Comment by displague** [comment]
After looking at this provider, I'd like to know more about the `accepter` resource.

The `accepter` (this is the resource name, which is a typo of `acceptor`) resource is used to create a `PATCH` API request to a given `ecx_l2_connection` resource (by `connection_id`).

Couldn't the `ecx_l2_connection` resource present "acceptance" as state?

```hcl
resource "ecx_l2_connection" "connection" {
 name = "tf-single-aws"
 profile_uuid = "2a4f7e27-dff8-4f15-aeda-a11ffe9ccf73"
 speed = 200
 speed_unit = "MB"
 notifications = ["marry@equinix.com", "john@equinix.com"]
 port_uuid = "febc9d80-11e0-4dc8-8eb8-c41b6b378df2"
 vlan_stag = 777
 vlan_ctag = 1000
 seller_region = "us-east-1"
 seller_metro_code = "SV"
 authorization_key = "1234456"

 # can these be sourced by the independent remote provider without any of the data above?
 access_key = foocloud_interconnect.bar.access_key
 secret_key =  foocloud_interconnect.bar.secret_key
}
```

**Comment by displague** [comment]
I followed the <= v0.12 documentation standard.

It looks like v0.13+ may have removed the need for `.html.markdown`: https://www.terraform.io/docs/registry/providers/docs.html#navigation-hierarchy

I'm not certain that the links I included in README.md will work correctly as is.  If this simple `.md` naming convention is in effect, Github may like that better as well.

**Comment by displague** [comment]
I see.. I will have to apply these changes: https://www.terraform.io/docs/registry/providers/docs.html#migrating-legacy-providers-docs

**Comment by mikouaj** [comment]
> After looking at this provider, I'd like to know more about the `accepter` resource.

Idea of this resource is to manage **accepter's side** (in this case AWS) of layer2 connection. 
You can find multiple examples of such resources in AWS provider i.e. [dx_hosted_private_virtual_interface_accepter](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dx_hosted_private_virtual_interface_accepter)

Goal of this particular `equinix_ecx_l2_connection_accepter` is to accept connection, originating from ECXF, on AWS side. Equinix is providing handy API for that, however same thing should be doable with AWS console / SDK / API.

According to @ocobleseqx - author of this resource - AWS TF provider is missing resource that provides such capability. In future, we can open PR to their provider code.


> Couldn't the `ecx_l2_connection` resource present "acceptance" as state?

I doubt that accepting connection on remote side (AWS in this case) is concern of ECXF connection resource.

**Review by mikouaj — APPROVED** [review]
that's awesome job

**Pull request merged**
