### PR TITLE
chore(dep): Updated fabric-go sdk usage for new fabric-go v0.7.0 version

### PR DESCRIPTION
**Pull request by thogarty**
* Gateway<...> methods renamed to CloudRouter<...>
* Service Profile Search Arguments updated to include `optional.string` for buyer/seller perspective. Adding nil defaults to aSide. Supporting Documentation: https://app.swaggerhub.com/apis/equinix-api/fabric/4.10.0#/Service%20Profiles/searchServiceProfiles
* Temporarily using version v0.7.0 from my fork, but once we release `fabric-go` we will update this to continue to use the main `fabric-go` repo. Fabric leadership requests this to decrease lag time for the Terraform release of `fabric-go` updates.
* Tested on Cloud Router Connection to Azure (tests the Cloud Router Renames and a Service Profile Search)

### CODE REVIEW

**Comment by t0mk** [comment]
@thogarty For some reason, the docs for the resource

**Comment by displague** [comment]
lgtm for the other bullets, which would make this a chore(dep) PR (updated the description to match that).

> Service Profile Search Arguments updated to include optional.string for buyer/seller perspective. Adding nil defaults to aSide. Supporting Documentation: https://app.swaggerhub.com/apis/equinix-api/fabric/4.10.0#/Service%20Profiles/searchServiceProfiles

I don't see that change here aside from adding in the extra nil param. Did you intend to expose the search criteria as parameters in the resource?

https://github.com/equinix/terraform-provider-equinix/pull/410/files#diff-83d074b4cffea56f9b980aa1aa2b1c864a5107d17942940f247f3d8b687079c3R286

**Review by displague — DISMISSED** [review]

**Comment by thogarty** [comment]
@displague , updated some recent example additions with `terraform fmt` as well. Did testing on multiCloudConnection to verify Fabric-Go Updates. Ran successfully.

Responding to your comment; I didn't think that it was necessary to add at this time. The terraform was already defaulting to searching as a buyer and this was to add feature parity with what was existing. 

Let me see what the effort would be to include it and if it's feasible I will. Otherwise I'll cut a follow up ticket.

**Review by srushti-patl — COMMENTED** [review]
LGTM

**Review by srushti-patl — APPROVED** [review]

**Review by displague — APPROVED** [review]
lgtm

There are a few more `terraform fmt --recursive` fixes to be made, which can happen in another PR.

The module changes (specifically the two removed variables in MultiCloudConnection) got me wondering about how valid each module is today. (This is also something we can address later.)


```
for a in $(find . -name main.tf  | sed s/main.tf//); do (cd $a; pwd; terraform init > /dev/null; terraform validate); done
```

## examples/fabric/v3/portConnectivity/equinix-metal-to-fabric-connection
```
╷
│ Warning: Deprecated Resource
│ 
│   with data.metal_project.this,
│   on main.tf line 10, in data "metal_project" "this":
│   10: data "metal_project" "this" {
│ 
│ Equinix Metal Provider is now Deprecated (End-of-Life scheduled for July 1, 2023) meaning that this software is only supported or maintained by Equinix Metal and its community in a
│ case-by-case basis. The Equinix provider (https://registry.terraform.io/providers/equinix/equinix/latest/docs) has full support for existing Terraform managed Metal resources once
│ Terraform configuration and state are adapted. The Equinix provider manages resources including Network Edge and Fabric in addition to Metal. Please review the Metal to Equinix provider
│ migration guide: https://registry.terraform.io/providers/equinix/equinix/latest/docs/guides/migration_guide_equinix_metal
│ 
│ (and one more similar warning elsewhere)
╵
```
Success! The configuration is valid, but there were some validation warnings as shown above.

## examples/fabric/v3/portConnectivity/oracle-cloud-connection
```
╷
│ Error: Reference to undeclared resource
│ 
│   on main.tf line 60, in resource "equinix_ecx_l2_connection" "oci-dot1q":
│   60:   profile_uuid      = data.equinix_ecx_l2_sellerprofile.oci.uuid
│ 
│ A data resource "equinix_ecx_l2_sellerprofile" "oci" has not been declared in the root module.
╵
```

## examples/fabric/v3/portConnectivity/public-profile
```
╷
│ Warning: Argument is deprecated
│ 
│   with equinix_ecx_l2_serviceprofile.seller-profile,
│   on main.tf line 14, in resource "equinix_ecx_l2_serviceprofile" "seller-profile":
│   14: resource "equinix_ecx_l2_serviceprofile" "seller-profile" {
│ 
│ TestProfile is no longer required and will be removed in a future release
╵
```
Success! The configuration is valid, but there were some validation warnings as shown above.


## examples/fabric/v3/portConnectivity/private-profile
```
╷
│ Warning: Argument is deprecated
│ 
│   with equinix_ecx_l2_serviceprofile.private-profile,
│   on main.tf line 15, in resource "equinix_ecx_l2_serviceprofile" "private-profile":
│   15: resource "equinix_ecx_l2_serviceprofile" "private-profile" {
│ 
│ TestProfile is no longer required and will be removed in a future release
╵
```
Success! The configuration is valid, but there were some validation warnings as shown above.


## examples/fabric/v4/cloudRouterConnectivity/multiCloudConnection
```
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 140, in resource "equinix_fabric_connection" "fcr2aws":
│  140:   additional_info = [{ "key" = "accessKey", "value" = var.aws_access_key }, { "key" = "secretKey", "value" = var.aws_secret_key }]
│ 
│ An argument named "additional_info" is not expected here. Did you mean to define a block of type "additional_info"?
╵
```
## examples/fabric/v4/cloudRouterConnectivity/cloudRouter2wan
```
╷
│ Error: Unsupported block type
│ 
│   on main.tf line 30, in resource "equinix_fabric_connection" "fcr2ipwan":
│   30:       network {
│ 
│ Blocks of type "network" are not expected here.
╵
```
## examples/fabric/v4/cloudRouterConnectivity/cloudRouter2aws
```
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 21, in resource "equinix_fabric_connection" "fcr2aws":
│   21:   additional_info = [{ "key" = "accessKey", "value" = var.aws_access_key }, { "key" = "secretKey", "value" = var.aws_secret_key }]
│ 
│ An argument named "additional_info" is not expected here. Did you mean to define a block of type "additional_info"?
╵
```

**Comment by thogarty** [comment]
@displague That's some interesting output. I know that at least for the `additional_info` argument I had some interesting questions about it during implementation. Might be valuable to get some more education on how to repeat that output for @srushti-patl and I and do some schema reviewing as well. There are some resource input instances that have my head scratching that I'm sure you all have already overcome.

For the service profile search update; I've checked the effort and I'm going to add that update in a follow up PR tomorrow. Should be in by MOD.

**Pull request merged**
