### PR TITLE
Add VRF Support

### PR DESCRIPTION
**Pull request by displague**
Related to: https://github.com/equinix/terraform-provider-metal/issues/220

* [x] Add Metal VRF Resource Support
  * [x] Datasource
  * [x] Docs (Resource and Datasource)
* [x] Add Metal VRF Support for IP Reservations
  * [x] Datasource
  * [x] Docs (Resource and Datasource)
* [x] Add Metal VRF Support for Metal Gateway devices
  * [x] Datasource
  * [x] Docs (Resource and Datasource)
* [x] Add Metal VRF Support for Metal Connection Virtual Circuits
  * [x] Docs (Resource and Datasource)

To run this branch locally:

```sh
OS="darwin" # or linux
ARCH="amd64"
VER=1.6.0-vrf
SOURCE=developer.equinix.com/equinix/equinix
PLUGIN_DIR=~/.terraform.d/plugins/${SOURCE}/${VER}/${OS}_${ARCH}/
cd ~/your-favorite-code-path
git clone https://github.com/equinix/terraform-provider-equinix
git checkout vrf
cd terraform-provider-equinix
make
mkdir -p $PLUGIN_DIR
cp terraform-provider-equinix $PLUGIN_DIR
```

Update your `required_versions` (usually in main.tf or versions.tf):
```hcl
terraform {
  required_providers {
    equinix = {
      # change this back to equinix/equinix  when not using this development build
      source = "developer.equinix.com/equinix/equinix"
      version = "1.6.0-vrf"
    }
  }
}
```

Example resources:
```hcl
resource "equinix_metal_vrf" "foo" {
	name = ...
        description = ...
	metro = ...
	project_id = ...
      	local_asn = "65000"
	ip_ranges = ["192.168.100.0/25"]
}

resource "equinix_metal_reserved_ip_block" "foo" {
	vrf_id = ...
	cidr = 29
	description = ...
	network = "192.168.100.0"
	type = "vrf"
	metro = ...
	project_id = ...
}
```

Find other examples in the `*acc_test.go` files.

### CODE REVIEW

**Comment by displague** [comment]
I'm seeing some failed tests related to the `POST /metal/v1/organizations` endpoint. This PR did not introduce any changes in the vicinity of that resource.

I've reached out for more information about why this has started failing (the `address` field seems to be the culprit).

**Comment by displague** [comment]
One final change needed is to update packngo in go.mod to the latest tagged release following https://github.com/packethost/packngo/pull/326.

This branch currently refers to a git commit in the packngo PR. Merging this PR without an update to a tagged packngo will be safe unless the packngo PR is rebased.

**Comment by displague** [comment]
I filed an issue related to some of the failed CI/CD tests: https://github.com/equinix/terraform-provider-equinix/issues/130

I attempted to correct some of this in this PR but there are more than I missed. I believe we should address these in a separate PR (accepting the changes that are already committed in this PR).

**Review by ocobleseqx — APPROVED** [review]
Approved after revision in a screen sharing session. Awesome job 👌🏻👌🏻

**Pull request merged**
