### PR TITLE
fix: Update Fabric Terraform Resources and Data sources for latest Fabric …

### PR DESCRIPTION
**Pull request by thogarty**
* Upgrade equinix-sdk-go to v0.46.0
* Update Port models to match changes in new Fabric SDK
* Update SimplifiedAccount to match changes in new Fabric SDK

### CODE REVIEW

**Review by srushti-patl — APPROVED** [review]

**Comment by thogarty** [comment]
Closes #798

**Comment by thogarty** [comment]
@ctreatma this should be released immediately to give customers a version that they can upgrade to once 4.17 API changes rollout. We do expect that early upgrades will break, but we would rather have that then not have a version available to customers that they can upgrade to for fixing the breaking issues.

The 4.17 API release is tomorrow evening (10/18)

**Review by displague — APPROVED** [review]
The release notes will need to include a note that all configurations with `equinix_fabric_port` and `equinix_fabric_ports` will need to updated to the latest version.

Migration notes will need to be included if the state will not be safely updated in-place.

**Comment by thogarty** [comment]
> The release notes will need to include a note that all configurations with `equinix_fabric_port` and `equinix_fabric_ports` will need to updated to the latest version.
> 
> Migration notes will need to be included if the state will not be safely updated in-place.

Agree. The state should be able to be updated with a refresh with no other changes than an upgrade. Just modifying internal functionality and not the Terraform interface. Additionally, for ports we have no resources.

Merging this in.

**Pull request merged**
