### PR TITLE
Import the Equinix Metal Terraform provider

### PR DESCRIPTION
**Pull request by displague**
This PR imports all of the resources from the Equinix Metal Terraform provider, preserving the history of the project.

Most of this import was mechanical, with search/replace and scripted `git mv` commands. 

Changes to equinix/provider.go, equinix/config.go, equinix/provider_test.go, equinix/config_test.go, and /main.go were minor but more hands-on.

The MPL2 licensed source from the Equinix Metal provider is relicensed as MIT to fit the Equinix provider. (Note: it is common for Terraform providers to be MPL2 licensed, following the pattern set by Hashicorp maintained providers and Terraform itself).

TODO and open questions:
* [ ] Add Equinix Metal API tokens to GH
* [ ] Remove vendor/ from the repo? (rewrite history to remove vendor/?)
* [ ] Remove metal deprecations (volumes, `PACKET_` variables, other features)
* [ ] Squash history?
* [ ] Relicense terraform-provider-equinix as MIT? Dual-license?
* [ ] Missing docs `layout` in any files?
* [ ] Use `subcategory: 'metal'` (and others) in docs?

### CODE REVIEW

**Comment by ocobleseqx** [comment]
> * [ ]  Use `subcategory: 'metal'` (and others) in docs?

I'd keep for now current dir structure

image

It will allow us to take advantage of the [plugin](https://github.com/hashicorp/terraform-plugin-docs)  to generate terraform provider docs whose output follows the same structure

image

https://www.terraform.io/registry/providers/docs#generating-documentation

using the generator will reduce workload and we can ensure that all resources appear in the registry and we don't forget any of them. It will also si

**Comment by ocobleseqx** [comment]
Additional tasks identified so far:

* [ ] Rename the metal data source files so they all follow the same pattern: datasource --> data_source_
* [ ] Redefine GH Actions so that it does not fail in each code push. In metal there was an action to run acceptance test on push. At this moment it is not possible to add this for Fabric/ne resources
* [ ] Split code into folders by product? It can help simplify management / independently handle behaviors for tests/actions/checks:

It could be:
```
          equinix/provider.go
          equinix/fabric/
          equinix/network_edge/
          equinix/metal/
```
Or a subfolder `services` like AWS and Azure providers:

```
          equinix/
          equinix/provider/
          equinix/services/fabric/
          equinix/services/network_edge/
          equinix/services/metal/
```

* [ ] Rename "_ecx_" files to "_fabric_"?

**Comment by displague** [comment]
@ocobleseqx Some of Hashicorp's modern providers (AWS, Azure) take the approach of internal/service/foo/foo_resource.go and internal/service/foo/foo_data_source.go.  The Azure provider splits functionality up further, `_import.go`.

>  Split code into folders by product? It can help simplify management / independently handle behaviors for tests/actions/checks:
>  Rename the metal data source files so they all follow the same pattern: datasource --> data_source_

I think we care come up with a more comprehensive refactoring after this is merged. s/datasource/data_source/ seems fine for now.

**Comment by displague** [comment]
Closing in favor of #95

**Pull request closed without merging**
